### ISSUE TITLE
抢不到 自动转 增加监控商品下单么？设置抢购时间可以设置到毫秒吗？希望老大增加一下

### ISSUE THREAD

**Issue by gzlee1985** [WongYuYe/jd_qianggou#1]
可以增加监控商品下单么？

**Comment by gzlee1985** [comment]
就是抢不到  可以转到监控有货提交订单   另外下单时间 自己可以设置精确到 毫秒？  例如 xx：xx：xx：xxx

**Comment by WongYuYe** [comment]
抢购时间毫秒级，感觉没啥必要。提前下单反而会触发频繁调用接口报错

**Comment by WongYuYe** [comment]
> 就是抢不到 可以转到监控有货提交订单 另外下单时间 自己可以设置精确到 毫秒？ 例如 xx：xx：xx：xxx

抢购时间毫秒级，感觉没啥必要。提前下单反而会触发频繁调用接口报错。
监控下单确实可以，我安排一下

**Comment by gzlee1985** [comment]
监控  次数  时间间隔   能自己设置  完美 感谢老大更新

**Comment by gzlee1985** [comment]
准点下单 时间不准 有时快有时慢 误差2-3秒 已经电脑同步京东时间

**Comment by gzlee1985** [comment]
下单时间例如 设置16:00：00  生成订单  是 02秒     然后设置58秒提交     提交有时01秒  00秒 有时 59秒 都有

**Comment by WongYuYe** [comment]
这个不是误差。。。
是因为下单需要走完下单流程，以jd v2版为例，需要调用三个接口，购物车全选->确认订单->提交订单，并且要等待每个接口回调返回，所以最后生成订单的时间延迟设置时间1~2秒，这1~2秒是这三个接口依次调用完的累计时间和。

**Comment by WongYuYe** [comment]
> 可以增加监控商品下单么？

v3版已加
