### ISSUE TITLE
请教，怎么想到使用nodejs来实现？

### ISSUE THREAD

**Issue by gorkys** [WongYuYe/jd_qianggou#5]
如题，nodejs在这方面是会有什么样的优势么？

**Comment by gzlee1985** [comment]
无论node js   还是PY  能实现基本抢购就可以了   node 打包EXE 夸平台会出去 找不到 浏览器目录

**Comment by WongYuYe** [comment]
> 如题，nodejs在这方面是会有什么样的优势么？

一开始想做个工具，使用者并不需要编码能力，打开即用。就选了python(简单的图形界面+打包能力)。实际开发过程中（边查api边开发），一些功能（如cookie自动获取），搞的都比较艰难，再加上考虑到后续功能添加，跨平台、目录结构等，就换了Node，同时自己也熟悉一点。
本质就是接口调用，对语言计算能力没啥要求，扩展能力考虑的更多点。

**Comment by WongYuYe** [comment]
> 无论node js 还是PY 能实现基本抢购就可以了 node 打包EXE 夸平台会出去 找不到 浏览器目录

node就不想打包了。。直接走网页

**Comment by gorkys** [comment]
黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。
原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh...
cookie之类的倒是有不少扫码获取的开源库，
另：话说jd里面的API都不带sign之类的加密参数？

**Comment by WongYuYe** [comment]
> 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。
> 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh...
> cookie之类的倒是有不少扫码获取的开源库，
> 另：话说jd里面的API都不带sign之类的加密参数？

cookie受教了。
jd的api确实没带sign。

**Comment by gorkys** [comment]
> > 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。
> > 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh...
> > cookie之类的倒是有不少扫码获取的开源库，
> > 另：话说jd里面的API都不带sign之类的加密参数？
> 
> cookie受教了。
> jd的api确实没带sign。

难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh...

**Comment by WongYuYe** [comment]
> > > 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。
> > > 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh...
> > > cookie之类的倒是有不少扫码获取的开源库，
> > > 另：话说jd里面的API都不带sign之类的加密参数？
> > 
> > 
> > cookie受教了。
> > jd的api确实没带sign。
> 
> 难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh...

别大佬。哈哈，交流还好。你说的监控，目前购物车内的能实现，除此之外的再得去抓抓接口。
发财项目嘛。。。买彩票吧，哈哈

**Comment by gorkys** [comment]
京东听说经常有一些BUG商品，除了监控最主要的就是线报渠道的优劣了。对京东这种大厂的平台都不敢想加密参数的难度，没想到居然没有，hhh...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 晚上10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5)





    
黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。
 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh...
 cookie之类的倒是有不少扫码获取的开源库，
 另：话说jd里面的API都不带sign之类的加密参数？
  
cookie受教了。
 jd的api确实没带sign。
  
难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh...
  
别大佬。哈哈，交流还好。你说的监控，目前购物车内的能实现，除此之外的再得去抓抓接口。
 发财项目嘛。。。买彩票吧，哈哈
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WongYuYe** [comment]
> 京东听说经常有一些BUG商品，除了监控最主要的就是线报渠道的优劣了。对京东这种大厂的平台都不敢想加密参数的难度，没想到居然没有，hhh...
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wang ***@***.***&gt;; 发送时间: 2021年8月19日(星期四) 晚上10:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5) 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh... cookie之类的倒是有不少扫码获取的开源库， 另：话说jd里面的API都不带sign之类的加密参数？ cookie受教了。 jd的api确实没带sign。 难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh... 别大佬。哈哈，交流还好。你说的监控，目前购物车内的能实现，除此之外的再得去抓抓接口。 发财项目嘛。。。买彩票吧，哈哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

BUG商品是什么意思，请教一下？

**Comment by gorkys** [comment]
就是有些类似于运营设置错价格的商品。有些商家也会硬着头皮发货，当然也有不会发货，补一些红包的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 晚上10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5)





  
京东听说经常有一些BUG商品，除了监控最主要的就是线报渠道的优劣了。对京东这种大厂的平台都不敢想加密参数的难度，没想到居然没有，hhh...
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wang @.&gt;; 发送时间: 2021年8月19日(星期四) 晚上10:44 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5) 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh... cookie之类的倒是有不少扫码获取的开源库， 另：话说jd里面的API都不带sign之类的加密参数？ cookie受教了。 jd的api确实没带sign。 难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh... 别大佬。哈哈，交流还好。你说的监控，目前购物车内的能实现，除此之外的再得去抓抓接口。 发财项目嘛。。。买彩票吧，哈哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
BUG商品是什么意思，请教一下？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WongYuYe** [comment]
> 就是有些类似于运营设置错价格的商品。有些商家也会硬着头皮发货，当然也有不会发货，补一些红包的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wang ***@***.***&gt;; 发送时间: 2021年8月19日(星期四) 晚上10:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5) 京东听说经常有一些BUG商品，除了监控最主要的就是线报渠道的优劣了。对京东这种大厂的平台都不敢想加密参数的难度，没想到居然没有，hhh... … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wang @.&gt;; 发送时间: 2021年8月19日(星期四) 晚上10:44 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [WongYuYe/jd_qianggou] 请教，怎么想到使用nodejs来实现？ (#5) 黑猫白猫能抓耗子就是好猫，不过在选型不是更应该选择更优的嘛。 原来如此，主要是感觉用nodejs来实现这类工具的比较少见。hhh... cookie之类的倒是有不少扫码获取的开源库， 另：话说jd里面的API都不带sign之类的加密参数？ cookie受教了。 jd的api确实没带sign。 难怪各种软件横行，不过7*24的监控各种bug商品应该算是个难点吧。大佬有啥发财项目带带弟弟，hhhh... 别大佬。哈哈，交流还好。你说的监控，目前购物车内的能实现，除此之外的再得去抓抓接口。 发财项目嘛。。。买彩票吧，哈哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. BUG商品是什么意思，请教一下？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WongYuYe** [comment]
这样子，感谢。
可以监控下近期的平均价，和当前价格，相差过大的就可能是这种BUG商品。目前很多比价插件可以爬到近期数据，应该还是有路子的。

**Comment by gorkys** [comment]
方便的话，可以加个Q之类的联系方式，可以交流一下。

**Comment by WongYuYe** [comment]
嗯，选几个监控就好

**Comment by WongYuYe** [comment]
q不常用，微信吧，wyuye_
